[SERV-1189] Add validator interface
UCLALibrary/validation-service pull request #31
Opened 2024-11-18 23:18 UTC by ksclarke

* Further parameterize parts of the Docker image build
* Update Docker image config to use patch version number too
* Use `exec` in ENTRYPOINT for better process control
* Add HEALTHCHECK to Docker image
* Add first passes at Validator and CsvLocation

2024-11-18 23:19 UTC, ksclarke commented
Draft because I think I'll have to make updates to the GAs too.

2025-01-11 00:41 UTC, angelahuqing commented on README.md
> +This is a microservice for CSV validation. It validations CSVs according to a prescribed set of rules. These rule
Should the sentence be "It validates CSVs"

2025-01-11 00:48 UTC, angelahuqing requested changes

2025-01-11 00:48 UTC, angelahuqing commented on csv_location_test.go
> +
More of a comment than a need to change. Tabular tests are really helpful for test cases like this. You can see examples in the [pt-tools](https://github.com/UCLALibrary/pt-tools) and [go-festerize](https://github.com/UCLALibrary/go-festerize) repos. I've mostly only written tabular tests so far in go.

2025-01-13 17:11 UTC, ksclarke commented on csv_location_test.go
> +
Just updating with result of Slack conversation Angela and I had: I deleted the test. It really wasn't useful since it was just testing a basic struct, which we can assume works as advertised.

2025-01-14 15:13 UTC, angelahuqing approved these changes

2025-01-14 23:29 UTC, DRickard approved these changes

2025-01-15 15:14 UTC, merged